# Generated by Django 5.2.5 on 2026-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_dailylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireresponse",
            name="course",
            field=models.CharField(
                choices=[("btech", "B.Tech"), ("bsc", "B.Sc")],
                default="btech",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="specialisation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
