# Generated by Django 5.2.5 on 2026-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_questionnaireresponse_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "course",
                    models.CharField(
                        choices=[("btech", "B.Tech"), ("bsc", "B.Sc")], max_length=10
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("notes", "Notes"),
                            ("video", "Video"),
                            ("article", "Article"),
                        ],
                        max_length=20,
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
