# Generated by Django 5.2.5 on 2026-02-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fuel_bonus",
            field=models.IntegerField(default=0),
        ),
    ]
