# Generated by Django 5.2.5 on 2026-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_profile_fuel_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_quest_completed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
